CREATE TABLE IF NOT EXISTS valid_results (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS binnary_results (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS timeout_errors (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);
