CREATE TABLE IF NOT EXISTS binnary_result (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS timeout_error (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS url_buffer (
	id INTEGER PRIMARY KEY,
	url VARCHAR(255) UNIQUE
);
